### ISSUE TITLE
How to load extensions into SQLite.jl

### ISSUE THREAD

**Issue by FabricioRHS** [JuliaDatabases/SQLite.jl#151]
Hello everyone, congratulations for the work.

How can I load an SQLite extension? In case I need to load the Spatialite. 
I've already tried via: `SQLite.query (db, "SELECT load_extension ('mod_spatialite');")`
but returns:` ERROR: SQLite.SQLiteException ("not authorized") `

I have checked `SQLite.query (db, 'SELECT sqlite_compileoption_used (' ENABLE_LOAD_EXTENSION ');") `and returned` 0`.

Could someone help me how could I load this extension? The libs are already in the environment variable (path)

Thanks in advance.

**Comment by JeremyBYU** [comment]
Hey I figured it out. You have to enable load extension.  Python has a direct API for it, but this Julia module seems to have it missing.  However you can call it the c-api.  Tested and it works for me.
```julia
using SQLite

db = SQLite.DB(":memory:")
# (Function name, string dll path), return value, (db handle data type, enable data type), db handle, true
ccall((:sqlite3_enable_load_extension, SQLite.libsqlite), Cint, (Ptr{Cvoid}, Cint), db.handle, 1)
SQLite.query(db, """SELECT load_extension('mod_spatialite');""");
SQLite.query(db, """SELECT InitSpatialMetaData();""");
qry = """SELECT name FROM sqlite_master
         WHERE type='table'
         ORDER BY name;"""

print(SQLite.query(db, qry))
```

**Comment by felipenoris** [comment]
This could be easily implemented as 

```julia
function enable_load_extension(db, flag::Bool)
   flag_int = flag ? 1 : 0
   ccall((:sqlite3_enable_load_extension, SQLite.libsqlite), Cint, (Ptr{Cvoid}, Cint), db.handle, 1)
end

**Comment by quinnj** [comment]
This is great stuff! Anyone care to do a PR to add this functionality?

**Comment by quinnj** [comment]
Thanks @felipenoris for the code; I just added this in #188
