### ISSUE TITLE
Pkg.add("SQLite") error on Julia 1.0.0

### ISSUE THREAD

**Issue by fatqi** [JuliaDatabases/SQLite.jl#155]
The error log as below:
julia> Pkg.add("SQLite")
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
   Cloning [944b1d66-785c-5afd-91f1-9de20f533193] CodecZlib from https://github.
com/bicycle1885/CodecZlib.jl.git
[ Info: Installed CodecZlib ──────────────────── v0.5.0
   Cloning [189a3867-3050-52da-a836-e630ba90ab69] Reexport from https://github.c
om/simonster/Reexport.jl.git
[ Info: Installed Reexport ────────────────────── v0.2.0
   Cloning [2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91] StatsBase from https://github.
com/JuliaStats/StatsBase.jl.git
[ Info: Installed StatsBase ──────────────────── v0.25.0
   Cloning [0aa819cd-b072-5ff4-a722-6bc24af294d9] SQLite from https://github.com
/JuliaDatabases/SQLite.jl.git
[ Info: Installed SQLite ────────────────────────── v0.6.0
......
  [1a1011a3] + SharedArrays
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  Building CodecZlib →→ `C:\Users\.julia\packages\CodecZlib\wwgbh\deps
\build.log`
┌┌ Error: Error building `CodecZlib`:
││ [ Info: Downloading https://github.com/bicycle1885/ZlibBuilder/releases/downl
oad/v1.0.2/Zlib.v1.2.11.x86_64-w64-mingw32.tar.gz to C:\Users\.julia\p
ackages\CodecZlib\wwgbh\deps\usr\downloads\Zlib.v1.2.11.x86_64-w64-mingw32.tar.g
z...
││ ERROR: LoadError: Could not download https://github.com/bicycle1885/ZlibBuild
er/releases/download/v1.0.2/Zlib.v1.2.11.x86_64-w64-mingw32.tar.gz to C:\Users\c
00467832\.julia\packages\CodecZlib\wwgbh\deps\usr\downloads\Zlib.v1.2.11.x86_64-
w64-mingw32.tar.gz:
││ ErrorException("")
││ Stacktrace:
││  [1] error(::String) at .\error.jl:33
││  [2] macro expansion at .\logging.jl:313 [inlined]
││  [3] #download#93(::Bool, ::Function, ::String, ::String) at C:\Users\c004678
32\.julia\packages\BinaryProvider\UTYxu\src\PlatformEngines.jl:443
││  [4] #download at .\none:0 [inlined]
││  [5] #download_verify#94(::Bool, ::Bool, ::Bool, ::Function, ::String, ::Stri
ng, ::String) at C:\Users\c00467832\.julia\packages\BinaryProvider\UTYxu\src\Pla
tformEngines.jl:523
││  [6] #download_verify at .\none:0 [inlined]
││  [7] #install#115(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::Function, ::S
tring, ::String) at C:\Users\.julia\packages\BinaryProvider\UTYxu\src\
Prefix.jl:353
││  [8] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:pref
ix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::S
tring) at .\none:0
││  [9] top-level scope at C:\Users\.julia\packages\CodecZlib\wwgbh\de
ps\build.jl:88
││  [10] include at .\boot.jl:317 [inlined]
││  [11] include_relative(::Module, ::String) at .\loading.jl:1038
││  [12] include(::Module, ::String) at .\sysimg.jl:29
││  [13] include(::String) at .\client.jl:388
││  [14] top-level scope at none:0
││ in expression starting at C:\Users\.julia\packages\CodecZlib\wwgbh\
deps\build.jl:81
││ ���á�SecurityProtocol��ʱ�����쳣쳣:������ö��ֵ��ЧЧ���޷�����ֵת��Ϊ���͡�Syst
││ em.Net.SecurityProtocolType������ָ������ö��ֵ֮һ��Ȼ�����ԡ����ܵ�ö��ֵΪ��
││ Ssl3��Tls������
││ ����λλ�� ��:1 �ַ�: 35
││ + [System.Net.ServicePointManager]:: <<<< SecurityProtocol =
││     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
││     + FullyQualifiedErrorId : PropertyAssignmentException
││
││ ʹ�á�2���������á�DownloadFile��ʱ�����쳣쳣:��Զ�̷�����ش���: (407) ��Ҫ
││ ���������֤����
││ ����λλ�� ��:5 �ַ�: 24
││ + $webclient.DownloadFile <<<< ("https://github.com/bicycle1885/ZlibBuilder/r
el
││ eases/download/v1.0.2/Zlib.v1.2.11.x86_64-w64-mingw32.tar.gz", "C:\Users\c004
67
││ 832\.julia\packages\CodecZlib\wwgbh\deps\usr\downloads\Zlib.v1.2.11.x86_64-w6
4-
││ mingw32.tar.gz")
││     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException

││     + FullyQualifiedErrorId : DotNetMethodException
││
└└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\b
uild\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1068
  Building SQLite ──────→→ `C:\Users\.julia\packages\SQLite\l2QaY\deps
\build.log`
┌┌ Error: Error building `SQLite`:
││ [ Info: Downloading https://github.com/JuliaDatabases/SQLiteBuilder/releases/
download/v0.9.0/SQLiteBuilder.v0.1.0.x86_64-w64-mingw32.tar.gz to C:\Users\c0046
7832\.julia\packages\SQLite\l2QaY\deps\usr\downloads\SQLiteBuilder.v0.1.0.x86_64
-w64-mingw32.tar.gz...
││ ERROR: LoadError: Could not download https://github.com/JuliaDatabases/SQLite
Builder/releases/download/v0.9.0/SQLiteBuilder.v0.1.0.x86_64-w64-mingw32.tar.gz
to C:\Users\c00467832\.julia\packages\SQLite\l2QaY\deps\usr\downloads\SQLiteBuil
der.v0.1.0.x86_64-w64-mingw32.tar.gz:
││ ErrorException("")
││ Stacktrace:
││  [1] error(::String) at .\error.jl:33
││  [2] macro expansion at .\logging.jl:313 [inlined]
││  [3] #download#93(::Bool, ::Function, ::String, ::String) at C:\Users
32\.julia\packages\BinaryProvider\UTYxu\src\PlatformEngines.jl:443
││  [4] #download at .\none:0 [inlined]
││  [5] #download_verify#94(::Bool, ::Bool, ::Bool, ::Function, ::String, ::Stri
ng, ::String) at C:\Users\.julia\packages\BinaryProvider\UTYxu\src\Pla
tformEngines.jl:523
││  [6] #download_verify at .\none:0 [inlined]
││  [7] #install#115(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::Function, ::S
tring, ::String) at C:\Users\c00467832\.julia\packages\BinaryProvider\UTYxu\src\
Prefix.jl:353
││  [8] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:pref
ix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::S
tring) at .\none:0
││  [9] top-level scope at C:\Users\.julia\packages\SQLite\l2QaY\deps\
build.jl:36
││  [10] include at .\boot.jl:317 [inlined]
││  [11] include_relative(::Module, ::String) at .\loading.jl:1038
││  [12] include(::Module, ::String) at .\sysimg.jl:29
││  [13] include(::String) at .\client.jl:388
││  [14] top-level scope at none:0
││ in expression starting at C:\Users\c00467832\.julia\packages\SQLite\l2QaY\dep
s\build.jl:32
││ ���á�SecurityProtocol��ʱ�����쳣쳣:������ö��ֵ��ЧЧ���޷�����ֵת��Ϊ���͡�Syst
││ em.Net.SecurityProtocolType������ָ������ö��ֵ֮һ��Ȼ�����ԡ����ܵ�ö��ֵΪ��
││ Ssl3��Tls������
││ ����λλ�� ��:1 �ַ�: 35
││ + [System.Net.ServicePointManager]:: <<<< SecurityProtocol =
││     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
││     + FullyQualifiedErrorId : PropertyAssignmentException
││
││ ʹ�á�2���������á�DownloadFile��ʱ�����쳣쳣:��Զ�̷�����ش���: (407) ��Ҫ
││ ���������֤����
││ ����λλ�� ��:5 �ַ�: 24
││ + $webclient.DownloadFile <<<< ("https://github.com/JuliaDatabases/SQLiteBuil
de
││ r/releases/download/v0.9.0/SQLiteBuilder.v0.1.0.x86_64-w64-mingw32.tar.gz", "
C:
││ \Users\c00467832\.julia\packages\SQLite\l2QaY\deps\usr\downloads\SQLiteBuilde
r.
││ v0.1.0.x86_64-w64-mingw32.tar.gz")
││     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException

││     + FullyQualifiedErrorId : DotNetMethodException
││
└└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\b
uild\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1068

Pls help me to fix this issue, I appreciate it.

**Comment by quinnj** [comment]
Sounds like an issue w/ the CodecZlib package; you could try rebuilding by doing `Pkg.build("SQLite")` and if it still doesn't work, file an issue with that package: https://github.com/bicycle1885/CodecZlib.jl/issues.

**Comment by felipenoris** [comment]
Actually, I guess this is a windows TLS issue: https://github.com/JuliaLang/julia/issues/26167
