### ISSUE TITLE
Mistake in Depwarn

### ISSUE THREAD

**Issue by sebastianpech** [JuliaDatabases/SQLite.jl#157]
https://github.com/JuliaDatabases/SQLite.jl/blob/ad1e2a04450dcfa2433931a7d4715c717514f8ad/src/Source.jl#L87

resultset, do `DataFrame(SQLite.query(db, sql))` instead
should actually be:
resultset, do `DataFrame(SQLite.Query(db, sql))` instead
with a capital letter Q.
Otherwise you still call the deprecated `SQLite.query` function.

**Comment by quinnj** [comment]
Thanks for opening the issue! I just pushed a fix for the deprecation message.
