### ISSUE TITLE
Access violation crashes kernel

### ISSUE THREAD

**Issue by ffmorais** [JuliaDatabases/SQLite.jl#161]
when i try to create a database but it seems i have no acesss to that folder i got a error and kernel crashes:
julia> db = SQLite.DB("C:\\Users\r11592\\TMIP\alarme.db")

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x663b8b72 -- sqlite3SafetyCheckSickOrOk at /workspace/srcdir/sqlite-autoconf-3240000\sqlite3.c:30683 [inlined]
sqlite3_errmsg at /workspace/srcdir/sqlite-autoconf-3240000\sqlite3.c:149127
in expression starting at no file:0
sqlite3_errmsg at /workspace/srcdir/sqlite-autoconf-3240000\sqlite3.c:149124
sqlite3_errmsg at C:\Users\r11592\.julia\packages\SQLite\xWe8d\src\api.jl:2 [inlined]
sqliteerror at C:\Users\r11592\.julia\packages\SQLite\xWe8d\src\SQLite.jl:21
Type at C:\Users\r11592\.julia\packages\SQLite\xWe8d\src\SQLite.jl:46
jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1831
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2184
do_call at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:324
eval_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:430
eval_stmt_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:363 [inlined]
eval_body at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:678
jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:795
unknown function (ip: FFFFFFFFFFFFFFFE)
unknown function (ip: 000000000CDB7C5F)
unknown function (ip: 0000000000000000)
jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:813
jl_toplevel_eval_in at /home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:622
eval at .\boot.jl:319
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2184
eval_user_input at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\REPL\src\REPL.jl:85
macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\REPL\src\REPL.jl:117 [inlined]
#28 at .\task.jl:259
jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2184
jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1537 [inlined]
start_task at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:268
Allocations: 76079393 (Pool: 76060894; Big: 18499); GC: 155

**Comment by ffmorais** [comment]
I saw that the error is on backslash missing, but kernel should be not crash

**Comment by mxkramer** [comment]
This happened for me as well on macOS when the directory that should contain the database doesn't exist.

**Comment by quinnj** [comment]
I can't seem to reproduce this at all on OSX; @mxkramer can you still reproduce? Sorry to be so slow in responding on this issue.

**Comment by mxkramer** [comment]
@quinnj I can't seem to. I can't remember what I was doing at the time, but currently if I run:

```
using SQLite
db = SQLite.DB("/some/fake/path")
```

I get:

```
ERROR: SQLite.SQLiteException("unable to open database file")
Stacktrace:
 [1] sqliteerror(::SQLite.DB) at /Users/Mia/.julia/packages/SQLite/msdQN/src/SQLite.jl:15
 [2] SQLite.DB(::String) at /Users/Mia/.julia/packages/SQLite/msdQN/src/SQLite.jl:40
 [3] top-level scope at REPL[7]:1
```

which seems expected.

**Comment by quinnj** [comment]
Thanks for checking @mxkramer; I'll close this for now and we can re-open if anybody sees it again.
