### ISSUE TITLE
Package build error with SQLite on Julia 0.6.4

### ISSUE THREAD

**Issue by anthonyagudelox3** [JuliaDatabases/SQLite.jl#175]
Hello,

I am having an issue when I attempting to build BioMedQuery on Julia 0.6.4 and get the following build error with one of BioMedQuery's dependencies SQLite. I am running the Julia on windows 10 machine.

Pkg.build("BioMedQuery")
INFO: Building CodecZlib
INFO: Building LibCURL
INFO: Building LightXML
INFO: Building MbedTLS
INFO: Building SpecialFunctions
INFO: Building DecFP
INFO: Building MySQL
INFO: Building Gumbo
INFO: Building WinRPM
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Building SQLite
INFO: Updating WinRPM package list
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Nothing to do
===================================================[ ERROR: SQLite ]====================================================

LoadError: Provider BinDeps.PackageManager failed to satisfy dependency sqlite3_lib
while loading C:\Users\Thor\.julia\v0.6\SQLite\deps\build.jl, in expression starting on line 19

========================================================================================================================

====================================================[ BUILD ERRORS ]====================================================

WARNING: SQLite had build errors.

 - packages with build errors remain installed in C:\Users\Thor\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("SQLite")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================

julia> Pkg.build("SQLite")
INFO: Building CodecZlib
INFO: Building WinRPM
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Building SQLite
INFO: Updating WinRPM package list
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Nothing to do
===================================================[ ERROR: SQLite ]====================================================

LoadError: Provider BinDeps.PackageManager failed to satisfy dependency sqlite3_lib
while loading C:\Users\Thor\.julia\v0.6\SQLite\deps\build.jl, in expression starting on line 19

========================================================================================================================

====================================================[ BUILD ERRORS ]====================================================

WARNING: SQLite had build errors.

 - packages with build errors remain installed in C:\Users\Thor\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("SQLite")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================

julia>

**Comment by quinnj** [comment]
Julia 0.6 is no longer officially supported; is there something holding you back from upgrading to Julia 1.0?

**Comment by anthonyagudelox3** [comment]
> Julia 0.6 is no longer officially supported; is there something holding you back from upgrading to Julia 1.0?

Yes, I currently have some scripts that I am working with that I have been having a hard time updating to the latest version.

**Comment by quinnj** [comment]
Ok, well I'm happy to help figure out how to port your scripts to 1.0 rather than try to support 0.6; it's been almost a full year w/ 1.0 released, and 1.2 is being released soon, so 0.6 is long gone in terms of being supported. Feel free to post issues you have here w/ 1.0 and I can try to help steer you in the right direction. There was also Julia 0.7 that was temporarily released to help transition code from 0.6 to 1.0 (w/ helpful error messages and deprecations and such).

**Comment by anthonyagudelox3** [comment]
Thanks Quinnj, I will start looking into transitioning to julia v1.0.0.

**Comment by anthonyagudelox3** [comment]
> Ok, well I'm happy to help figure out how to port your scripts to 1.0 rather than try to support 0.6; it's been almost a full year w/ 1.0 released, and 1.2 is being released soon, so 0.6 is long gone in terms of being supported. Feel free to post issues you have here w/ 1.0 and I can try to help steer you in the right direction. There was also Julia 0.7 that was temporarily released to help transition code from 0.6 to 1.0 (w/ helpful error messages and deprecations and such).

Although in the meantime, as I am working on submitting a paper within the next few weeks, I was curious if there was anywhere I could find an older version of the package. 

Thank you, 
Anthony Agudelo

**Comment by anthonyagudelox3** [comment]
> Ok, well I'm happy to help figure out how to port your scripts to 1.0 rather than try to support 0.6; it's been almost a full year w/ 1.0 released, and 1.2 is being released soon, so 0.6 is long gone in terms of being supported. Feel free to post issues you have here w/ 1.0 and I can try to help steer you in the right direction. There was also Julia 0.7 that was temporarily released to help transition code from 0.6 to 1.0 (w/ helpful error messages and deprecations and such).

Also it seems that another package, Mocha.jl, that my code utilizes does not work with Julia v0.7.0 and Julia v1.0.0

**Comment by DilumAluthge** [comment]
Mocha.jl is no longer supported.

I recommend that you check out [Flux.jl](https://github.com/FluxML/Flux.jl) and [Knet.jl](https://github.com/denizyuret/Knet.jl)

**Comment by anthonyagudelox3** [comment]
Running this line of code on Julia 1.1.1;

`df_temp = df[findin(df[:pmid],pmids),:]`

It gives the following error;

```
ERROR: LoadError: UndefVarError: findin not defined
Stacktrace:
 [1] remove_columns_constant_for_pmids(::DataFrame, ::Array{Int32,1}) at C:\Users\Thor\Documents\Machine Learning\Work\feature_selection3.jl:1168
 [2] test_analysis_skl(::DataFrame, ::Array{Int32,1}, ::Array{Int32,1}, ::Symbol, ::Dict{Symbol,Any}) at C:\Users\Thor\Documents\Machine Learning\Work\crossval_and_stats.jl:21
 [3] main() at C:\Users\Thor\Documents\Machine Learning\Work\machine_learning_regsampling.jl:79
 [4] top-level scope at none:0
 [5] include at .\boot.jl:326 [inlined]
 [6] include_relative(::Module, ::String) at .\loading.jl:1038
 [7] include(::Module, ::String) at .\sysimg.jl:29
 [8] exec_options(::Base.JLOptions) at .\client.jl:267
 [9] _start() at .\client.jl:436
in expression starting at C:\Users\Thor\Documents\Machine Learning\Work\machine_learning_regsampling.jl:181
```
Note: df is a Dataframe.

findin() is undefined in julia 1.1.1, I was wondering if there was another function I could use or perhaps a package that makes the findin() function defined?

**Comment by quinnj** [comment]
Closing as no longer relevant
