### ISSUE TITLE
Multiline statements do not work

### ISSUE THREAD

**Issue by ohmsweetohm1** [JuliaDatabases/SQLite.jl#186]
The following [example](https://www.sqlitetutorial.net/sqlite-transaction/):
```julia
using SQLite

sql = "
CREATE TABLE accounts ( 
    account_no INTEGER NOT NULL, 
    balance DECIMAL NOT NULL DEFAULT 0
);
 
CREATE TABLE account_changes (
    change_no INT NOT NULL PRIMARY KEY,
    account_no INTEGER NOT NULL, 
    flag TEXT NOT NULL, 
    amount DECIMAL NOT NULL, 
    changed_at TEXT NOT NULL 
);
"
db = SQLite.DB("test.db")

SQLite.execute!(db, sql)
```
does not create the correct SQLite db.

**Comment by ohmsweetohm1** [comment]
It seems that `execute!` only takes one SQL statement at a time.

**Comment by quinnj** [comment]
Currently, we just pass whatever the input string is straight to the sqlite engine. We could potentially split the input string on `;` and loop through the results. Maybe we just do that for `SQLite.execute!` though, since it wouldn't really make sense for `SQLite.query`.

**Comment by quinnj** [comment]
sqlite doesn't really offer great support for this
