### ISSUE TITLE
SQLiteException - "duplicate column name"

### ISSUE THREAD

**Issue by kescobo** [JuliaDatabases/SQLite.jl#193]
I have a DataFrame that I'm trying to load into a `sqlite` table:

```
julia> SQLite.drop!(db, "widemetadata", ifexists=true)

julia> widedf |> SQLite.load!(db, "widemetadata") 
ERROR: SQLite.SQLiteException("duplicate column name: collectionInitials")                                                      
Stacktrace:                                                                                                                     
 [1] sqliteerror(::SQLite.DB) at /home/kevin/.julia/packages/SQLite/msdQN/src/SQLite.jl:15                                      
 [2] macro expansion at /home/kevin/.julia/packages/SQLite/msdQN/src/consts.jl:21 [inlined
[3] sqliteprepare at /home/kevin/.julia/packages/SQLite/msdQN/src/SQLite.jl:77 [inlined]                                        [4] SQLite.Stmt(::SQLite.DB, ::String) at /home/kevin/.julia/packages/SQLite/msdQN/src/SQLite.jl:64                             [5] execute!(::SQLite.DB, ::String) at /home/kevin/.julia/packages/SQLite/msdQN/src/SQLite.jl:257                               [6] #createtable!#20(::Bool, ::Bool, ::typeof(SQLite.createtable!), ::SQLite.DB, ::String, 
#... lots more
```

I definitely don't have any duplicate column names:

```
julia> length(names(widedf))
781

julia> length(names(widedf)|>unique)
781
```

I tried

```
julia> widedf[!,Not([:collectionInitials])] |> SQLite.load!(db, "widemetadata")
ERROR: SQLite.SQLiteException("duplicate column name: LifeStage") 
#... etc
```

I thought maybe it was due to the size of the DataFrame, but `LifeStage` is way further on than `:collectionInitials`:

```
julia> findfirst(x-> x==:collectionInitials, names(widedf))
444                           
                                                                                                                                
julia> findfirst(x-> x==:LifeStage, names(widedf))
498
```

Thoughts?

**Comment by quinnj** [comment]
Hey @kescobo, sorry this slipped through the cracks somehow; do you have the sqlite file/db to reproduce this? I'd love to dig into this and figure out what's going on before doing another release.

**Comment by kescobo** [comment]
E-mailed a CSV and an SQLite database plus some code to re-generate the wide DataFrame. Hope you can figure it out!

**Comment by quinnj** [comment]
So it turns out the issue here is that column and table names are case-insensitive in sqlite, so the error I see on the file @kescobo sent is duplicate column names for `dateShipped` and `DateShipped`. I wonder if we should check this ourselves and throw a more informative error or maybe give a way to tweak the column names so the table can still be loaded (like appending 1 to `dateshipped1`). Thoughts?

**Comment by kescobo** [comment]
Doesn't DataFrames use a strategy of throwing an error by default, but giving a kwarg that allows it to be more permissive? I've come around to the idea of safety first, especially when it comes to data (I didn't think to look at capitalization, because surely my collaborators wouldn't use different cases in different situations, right? 🤦‍♂ 

I'm not sure how much performance would be lost with this sort of check, but if it's reasonable I think more informative error messages are always nice :-)
