### ISSUE TITLE
Add iterate to SQLite.row

### ISSUE THREAD

**Issue by kescobo** [JuliaDatabases/SQLite.jl#198]
From Slack - this recently stopped working:

```
for (feature, value) in SQLite.Query(db, my_query)
# ...
```

Where my_query returns a 2-column table. It now causes `ERROR: MethodError: no method matching iterate(::SQLite.Row)`.

It works if instead I do

```
for r in SQLite.Query(db, my_query)
    (feature, value) = (r[1], r[2])
# ...
```

@quinnj suggested it's [this commit](https://github.com/JuliaDatabases/SQLite.jl/commit/4f3fab2043a534aa3a16e639aa96de1a8d4bc574)

**Comment by quinnj** [comment]
Added in https://github.com/JuliaDatabases/SQLite.jl/pull/196
