### ISSUE TITLE
Docs where not updated

### ISSUE THREAD

**Issue by felipenoris** [JuliaDatabases/SQLite.jl#203]
Looks like the docs at https://juliadatabases.github.io/SQLite.jl/stable/ were not updated to version v1.0.0 of the package. It shows the version 0.8.2 .

As an example, the method `execute!` still appears in the docs.

**Comment by felipenoris** [comment]
Hi @quinnj ! Looks like travis CI stopped running since Oct 15 2019 (commit eb24e4ca5acfadce25b0cbc8563c289f1437f65f). Are you moving to github CI?

**Comment by quinnj** [comment]
Not sure what happened; I reset the travis settings and it seems to be working now. Just tagged a new release that will build the right stable docs (dev is already updated)

**Comment by felipenoris** [comment]
Great! Thanks!
