### ISSUE TITLE
ERROR: MethodError: no method matching SQLite.Query(::SQLite.DB, ::String)

### ISSUE THREAD

**Issue by adamryczkowski** [JuliaDatabases/SQLite.jl#205]
Since SQLite@1.0.0 I get the following error:

```julia
import SQLite
julia> db = SQLite.DB("/home/adam/db.sqlite")
SQLite.DB("/home/adam/db.sqlite")
julia> sql="""SELECT COUNT(*) as count FROM mytable"""
"SELECT COUNT(*) as count FROM mytable"
julia> df = SQLite.Query(db, sql)
ERROR: MethodError: no method matching SQLite.Query(::SQLite.DB, ::String)
Closest candidates are:
  SQLite.Query(::Any, ::Any, ::Any, ::Any, ::Any) at /home/adam/.julia/packages/SQLite/6uY89/src/tables.jl:6
Stacktrace:
 [1] top-level scope at none:0
```

The same code worked on SQLite@0.9.0. 

I use Julia 1.3.1

**Comment by ImreSamu** [comment]
maybe ...
-------------
_"For SQLite.jl, there were two breaking changes introduced, including:_
* `SQLite.execute!` is now just `SQLite.execute`
* `SQLite.Query` is now `DBInterface.execute`: for executing and returning query results
""

https://discourse.julialang.org/t/ann-dbinterface-jl-mysql-jl-1-0-and-sqlite-jl-1-0/34701
see : https://github.com/JuliaDatabases/SQLite.jl/blob/master/test/runtests.jl#L41

**Comment by quinnj** [comment]
Yes, @ImreSamu is correct; the 1.0 release is a new major release, w/ two breaking changes as mentioned in the discourse announcement.

**Comment by adamryczkowski** [comment]
IMHO you should reflect this change in the documentation.

**Comment by quinnj** [comment]
Yes, unfortunately there was a bug in the travis CI workflow that prevented new docs from being deployed for 1.0; this has been fixed and once the new tag has been released/built, the stable docs will be updated (dev docs are already updated)

ref: https://github.com/JuliaDatabases/SQLite.jl/issues/203
