### ISSUE TITLE
libsqlite3.so.0 causes crash of other packages 

### ISSUE THREAD

**Issue by htyeim** [JuliaDatabases/SQLite.jl#214]
It seems that after `using SQLite`, the `libsqlite3.so` provided by `SQLite_jll` will replace the `libsqlite3` in `/usr/lib` then breaks some other packages.

For example when `SQLite.jl` and `GMT.jl` are used together, the error below will rise:
```
ERROR: could not load library "/usr/lib/libgmt.so"
/usr/bin/../lib/libgdal.so.26: undefined symbol: sqlite3_column_table_name
Stacktrace:
 [1] GMT_Create_Session at /home/t/.julia/packages/GMT/oeYJl/src/libgmt.jl:26 [inlined] (repeats 2 times)
 [2] gmt(::String, ::Nothing) at /home/t/.julia/packages/GMT/oeYJl/src/gmt_main.jl:125
 [3] makecpt(::String, ::Nothing; kwargs::Base.Iterators.Pairs{Symbol,Symbol,Tuple{Symbol},NamedTuple{(:color,),Tuple{Symbol}}}) at /home/t/.julia/packages/GMT/oeYJl/src/makecpt.jl:92
 [4] top-level scope at REPL[3]:1
caused by [exception 1]
UndefVarError: API not defined
Stacktrace:
 [1] gmt(::String, ::Nothing) at /home/t/.julia/packages/GMT/oeYJl/src/gmt_main.jl:122
 [2] makecpt(::String, ::Nothing; kwargs::Base.Iterators.Pairs{Symbol,Symbol,Tuple{Symbol},NamedTuple{(:color,),Tuple{Symbol}}}) at /home/t/.julia/packages/GMT/oeYJl/src/makecpt.jl:92
 [3] top-level scope at REPL[3]:1
```
But if I only use `GMT` then all things are work fine.

The reason seems related to the `libsqlite3.so.0` which is downloaded from https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases (SQLite.v3.31.1.x86_64-linux-gnu in my case).

If `nm -D libsqlite3.so.0 | grep sqlite3_column_table`  is run for the so file above, there is no output.
But when the same command is run for libsqlite3 in `/usr/bin` (Archlinux in my case), it will give:
```
 /usr/lib  nm -D libsqlite3.so.0 | grep sqlite3_column_table
00000000000d83f0 T sqlite3_column_table_name
00000000000d8490 T sqlite3_column_table_name16
```

I don't know if it is a problem related to the so file provided by `SQLite_jll`. And also it seems sqlite has been updated to [3.32.3](https://www.sqlite.org/releaselog/3_32_3.html). I don't if there is any plan to update the `SQLite_jll`

**Comment by quinnj** [comment]
@staticfloat, @giordano, does anything here ring a bell for you? I'm almost positive that the BinaryBuilder-provided shared library couldn't "replace" a system library. It seems most likely that GMT.jl has an undeclared dependency on sqlite that we should figure out. We should also do the sqlite update for sure.

**Comment by giordano** [comment]
The solution is clearly to build gmt with BinaryBuilder :slightly_smiling_face: 

@htyeim  Where is this libgmt coming from?

**Comment by giordano** [comment]
@htyeim if you update the package you should get `SQLite_jll` v3.32.3+0 which I'm confident will fix your issue.

**Comment by htyeim** [comment]
```
(@v1.4) pkg> add SQLite_jll
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
  Installed SQLite_jll ─ v3.32.3+0
Downloading artifact: SQLite
   Updating `~/.julia/environments/v1.4/Project.toml`
  [76ed43ae] + SQLite_jll v3.32.3+0
   Updating `~/.julia/environments/v1.4/Manifest.toml`
  [76ed43ae] ↑ SQLite_jll v3.31.1+0 ⇒ v3.32.3+0

julia> using SQLite
[ Info: Precompiling SQLite [0aa819cd-b072-5ff4-a722-6bc24af294d9]

julia> using GMT

julia> makecpt(color=:jet)
GMT.GMTcpt([0.0 0.0 0.4980392156862745; 0.0 0.0 1.0; … ; 1.0 0.0 0.0; 0.4980392156862745 0.4980392156862745 0.4980392156862745], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0 0.125; 0.125 0.375; … ; 0.625 0.875; 0.875 1.0], [0.0, 1.0], [0.0 0.0 0.0; 1.0 1.0 1.0; 0.5 0.5 0.5], 24, NaN, [0.0 0.0 … 0.0 1.0; 0.0 0.0 … 1.0 1.0; … ; 1.0 1.0 … 0.0 0.0; 1.0 0.0 … 0.0 0.0], "rgb", String[])

julia> 

```
-------------------

Yes! It has been solved! Thank you!

The libgmt.so was built from [AUR](https://aur.archlinux.org/packages/gmt6/) in Archlinux and brew in macOS in my personal case. And I didn't change anything (it's beyond my knowledge...)
I indeed did try to build gmt with BinaryBuilder. But after providing `https://github.com/GenericMappingTools/gmt.git` and 6.1.0 tag, selecting platform, when entered the `/workspace/srcdir` directory, I had no idea how to do... I think that [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gmt6) would help. But it again is beyond my knowledge :rofl: 

As a user of Julia, I have almost rewritten all my code (Python, Matlab, CPP etc) in Julia and I definitely hope that someone with enough knowledge about this could have a try to build gmt with BinaryBuilder~

BTW, as the problem has been solved I'm closing this issue
