### ISSUE TITLE
Exception when opening sqlite DB with blobs

### ISSUE THREAD

**Issue by ceesb** [JuliaDatabases/SQLite.jl#222]
I'm getting this exception when opening a database that contains a lot of binary blobs, and wasn't created with Julia's SQLite. Is there a way to open a DB without deserializing blobs to Julia types? I just want to access them as Vector{UInt8}.

https://github.com/JuliaDatabases/SQLite.jl/blob/a826caa0517d48ae46e69e37cc181dc279fe62a9/src/SQLite.jl#L247

**Comment by quinnj** [comment]
This should have been fixed in https://github.com/JuliaDatabases/SQLite.jl/pull/249
