### ISSUE TITLE
Please provide more comprehensive docs for execute

### ISSUE THREAD

**Issue by maxfreu** [JuliaDatabases/SQLite.jl#233]
Hi! I'm not used to work with databases, so total noob: It would be cool to have a minimal context of the `execute()` function in the docs, so that I can exactly see what is meant by `params` and how to use it. Thanks :)

**Comment by quinnj** [comment]
Could you clarify a bit? We have the docs [here](https://juliadatabases.org/SQLite.jl/stable/#DBInterface.execute) that specifically mention `params` and such. Is there something unclear there? We always welcome pull requests to update docs; it's easy to if you go to [this page](https://github.com/JuliaDatabases/SQLite.jl/blob/master/docs/src/index.md) and you can edit directly

**Comment by maxfreu** [comment]
I think I made two mistakes: 
1) I used `SQLite.execute()` instead of `DBInterface.execute()`, because I didn't look close enough and wondered why I'm only getting `100` back (everything is `SQLite...` except execute, which tripped me up). This made me think I did sth wrong and I need to provide `params` somehow...
2) but now after reading the DBInterface front page I realized that `params` are only needed for `INSERT` statements (or others which I don't know), not for `SELECT` which I used. (Correct?)

So maybe one could simply add a one-liner to the `execute` docs, pointing to the DBInterface docs, e.g. 
"Please take a look at the [DBInterface.jl](https://github.com/JuliaDatabases/DBInterface.jl) readme / documentation for usage examples."

So close this at your descretion :)

**Comment by quinnj** [comment]
Yes, `params` are usually only for `INSERT` statements, though theoretically you could do something like `stmt = DBInterface.prepare(db, "select * from tbl where id = ?")` and then you could execute a query multiple times, passing a different `id` each time.

**Comment by quinnj** [comment]
I always welcome documentation updates, so feel free to make a PR if you'd like!
