### ISSUE TITLE
Select col from sys.tables?

### ISSUE THREAD

**Issue by ixzh** [JuliaDatabases/SQLite.jl#235]
Execution fails with "SQLite.SQLiteException("no such table: sys.tables")". Any documentation on cross tables select?

**Comment by quinnj** [comment]
What is "cross tables select"? If you're trying to query system tables, you can do, for example:

```julia
using Tables, SQLite, DBInterface
tbl = DBInterface.execute(db, "select * from sqlite_master") |> columntabe
```

**Comment by ixzh** [comment]
yes I was to select all tables containing a specific column. sqlite_master is the way thanks will close.😂
