### ISSUE TITLE
Any plans for an ORM?

### ISSUE THREAD

**Issue by aiqc** [JuliaDatabases/SQLite.jl#238]
Are there any plans for an object relational model (ORM)? I've been using peewee to interface with SQLite and it's fantastic.

http://docs.peewee-orm.com/en/latest/peewee/quickstart.html#model-definition

**Comment by quinnj** [comment]
I'm not aware of any specific plans. I personally just use the [Strapping.jl](https://github.com/JuliaData/Strapping.jl) package, which provides the translation between model objects and 2D columnar format. Specifically `Strapping.deconstruct` translates a `Vector{T}`, where `T` is my model object, to a Tables.jl compatible source, which can be loaded into an sqlite table via `SQLite.load`. Then you can use `Strapping.construct(T, DBInterface.execute(db, query))` to translate from database results back to model object.
