### ISSUE TITLE
Broken regex in `juliatype` v1.1.4?

### ISSUE THREAD

**Issue by dvasya** [JuliaDatabases/SQLite.jl#242]
After updating SQLite I'm getting the warning:

> ┌ Warning: 2021-05-11 14:22:20 Unsupported SQLite declared type VARCHAR, falling back to String type
> └ @ SQLite ~/.julia/packages/SQLite/jf6KT/src/SQLite.jl:397

SQLite.jl in v1.1.4, line 392-393, reads:
```
    elseif occursin(r"^(?:N?VAR)?CHAR\(\d+\)$", typeuc)
        return String`

```

however, 
```
julia> occursin(r"^(?:N?VAR)?CHAR\(\d+\)$", "VARCHAR")
false
```

Looks like a bug in this regex. What cases was it supposed to cover?

**Comment by quinnj** [comment]
Thanks for reporting and sorry for the delay in fixing. Fix is up: https://github.com/JuliaDatabases/SQLite.jl/pull/264
