### ISSUE TITLE
Incorrect handling of string types with length limits

### ISSUE THREAD

**Issue by essenciary** [JuliaDatabases/SQLite.jl#245]
It looks like for string types with character limit (eg `VARCHAR (100)`, `TEXT (100)` etc. 

These are not enforced by SQLite and are provided only for SQL compatibility, but they are "legal". 

However, this throws a warning at it shouldn't. 

![image](https://user-images.githubusercontent.com/11292378/121931188-928ab980-cd43-11eb-959c-a8a982836d17.png)

These types arrive in Julia with their limits: 
`Unsupported SQLite declared type TEXT (100)`

**Comment by quinnj** [comment]
@alyst, should just need some tweaks on the new type handling code?

**Comment by alyst** [comment]
@quinnj Yes, [here](https://github.com/JuliaDatabases/SQLite.jl/blob/master/src/SQLite.jl#L392) it should be changed into something like
```
occursin(r"^((?:N?VAR)?CHAR|TEXT)\s?\(\d+\)$", typeuc)
```

**Comment by quinnj** [comment]
Thanks for the report @essenciary and sorry for the delay in fixing. Fix is here: https://github.com/JuliaDatabases/SQLite.jl/pull/264
