### ISSUE TITLE
New release to support WeakRefStrings version 1.0

### ISSUE THREAD

**Issue by metab0t** [JuliaDatabases/SQLite.jl#257]
A new `SQLite.jl` release should be made to support `WeakRefStrings.jl` version 1.0, so it won't block update of `CSV.jl`.

**Comment by quinnj** [comment]
It already has declared compat for WeakRefStrings 1; see [here](https://github.com/JuliaDatabases/SQLite.jl/blob/dd145465e1d677fd4d78f74c725d52b4db551367/Project.toml#L23)

**Comment by metab0t** [comment]
I mean that this new change is not included in current release v1.1.4.

**Comment by quinnj** [comment]
Oh, my bad! I didn't realize we haven't had a release in a while. New release just tagged.
