### ISSUE TITLE
SQLite 1.2.0's load! eats the first row of rows in the unknown schema case

### ISSUE THREAD

**Issue by geoffleyland** [JuliaDatabases/SQLite.jl#259]
`load!` gets the first row of rows to discover field names, but then passes the (once iterated) rows to the version of load! with a schema, and the first row never gets inserted.
A workaround is to provide a schema, but no schema is broken for now.

**Comment by quinnj** [comment]
Thanks for the report @geoffleyland and sorry for the hassle here; definitely a bug/miss in the code. Fix is up: https://github.com/JuliaDatabases/SQLite.jl/pull/260
