### ISSUE TITLE
BLOB Truncation in Results

### ISSUE THREAD

**Issue by binarybana** [JuliaDatabases/SQLite.jl#28]
I haven't had a chance to debug this fully, but I was seeing about 1/4 of my rows of BLOB fields resulting in prematurely truncated values. In Python they would turn out fine (these were zlib compressed JSON), but in Julia it would result in decompressed strings that were truncated.

I haven't had time to look into it more, (eg: it could also be the fault of the Zlib.jl library, but I doubt it) so this is partially as a reminder to myself, but I thought I'd put it here before I forgot about it.

**Comment by binarybana** [comment]
Unfortunately, the new overhaul code is still vulnerable to this bug:
c.py:
```python
import sqlite3
conn = sqlite3.connect('test.db')
conn.text_factory = str
conn.execute("CREATE TABLE blobtest (a BLOB, b BLOB)")
conn.execute("INSERT INTO blobtest VALUES (?,?)", ("\xa5te\x00st", '\x92\x01\x02'))
print(conn.execute("SELECT * from blobtest").fetchall())
conn.commit()
conn.close()
```

f.jl:
```julia
using MsgPack
using SQLite

conn = SQLiteDB("test.db")
x = query(conn, "SELECT * from blobtest")
@show x
println(typeof(x[1]))
```

Results in:
```
$ rm -f test.db; python c.py; julia f.jl
[('\xa5te\x00st', '\x92\x01\x02')]
3
SQLITE_TEXT => 3
SQLITE_BLOB => 4
3
SQLITE_TEXT => 3
SQLITE_BLOB => 4
x => 1x2 ResultSet
| Row | "a"   | "b"   |
|-----|-------|-------|
| 1   | "�te" | "�\x01\x02" |
Array{Any,1}
```

Where I have instrumented src/SQLite.jl to print out the result of sqlite3_column_type [here](https://github.com/quinnj/SQLite.jl/blob/master/src/SQLite.jl#L214) so that you can see the blob column being interpreted as a text column and the truncation occurring in the resultset. 

I have no idea why this is occurring, because PRAGMA table_info(blobtest) clearly shows:
```
0|a|BLOB|0||0
1|b|BLOB|0||0
```

which is identical to the Julia-only blob tests in the tests. But it could easily catch someone out who is using SQLite databases from Julia and Python.

**Comment by binarybana** [comment]
Ahh! Nevermind. Apparently you have to pass in ``buffer`` to the insert statement in python in order to get it to be a ``BLOB``. Argh dynamic typing...

Sorry for the noise, and thanks for the nice overhaul btw!

**Comment by Sean1708** [comment]
Good to hear! Depending on how your application works [adapters](https://docs.python.org/3.4/library/sqlite3.html#using-adapters-to-store-additional-python-types-in-sqlite-databases) might be useful here.

**Comment by binarybana** [comment]
Thanks for the tip @Sean1708, for now a simple ``buffer`` conversion works for me, but I'll keep that in mind.

**Comment by hrobotron** [comment]
Another workaround: SELECT cast(field as blob) FROM ... just used it for text->blob conversion, no idea how efficient it is, but internal storage for text vs. blob in sqlite is the same.
