### ISSUE TITLE
Support for begin/commit statements?

### ISSUE THREAD

**Issue by paulmelis** [JuliaDatabases/SQLite.jl#292]
Looking at #246 it seems the only real transaction control is using `executemany`, when working through `DBInterface`? What about support for explicit [`begin` and `commit`](https://www.sqlite.org/lang_transaction.html) to control transactions? This works pretty well in Python's `sqlite3` (and `begin` will disable the auto-commit at that point to give control). Preparing a large number of insert/update statements isn't really feasible in all cases (nor a very nice way of writing the code).

**Comment by quinnj** [comment]
Take a look at the docs for `SQLite.transaction` (for begin), and `SQL.commit` for commit. There's also `SQLite.rollback` for rolling back, and `SQLite.transaction(f, db)` for doing a begin, executing the function `f()`, then calling commit, unless an error is thrown, then we call rollback. Hope that helps!

**Comment by paulmelis** [comment]
Thanks for the tip, but I did search the docs for both the words "transaction" and "commit", but that does not show any results.
