### ISSUE TITLE
Stale statements with DBInterface @prepare

### ISSUE THREAD

**Issue by glchapman** [JuliaDatabases/SQLite.jl#301]
I'm using an in-memory database for testing, with multiple test groups where the database is created/destroyed around each group's tests. I was also using some Stmt's created using @prepare from DBInterface. This was resulting in test failures with exceptions like
```
SQLite.SQLiteException("Statement 2 not found")
```
I believe the problem was that the Stmt's cached in DBInterface's PREPARED_STMTS were not freed when the test database was destroyed; trying to use them with a freshly created database failed because there was no corresponding _StmtId in the Sqlite.DB. At any rate, I rewrote my code to remove uses of @prepare, and the problem was solved.

Perhaps this is worth a warning in the Sqlite package's documentation.

**Comment by metab0t** [comment]
Can you provide a code snippet for reproduction?

**Comment by glchapman** [comment]
Looking further at this, I realize the only problem was my misconception of the `@prepare` macro. I was thinking of it as a memoized `prepare(conn, sql)` and was using a SQLite.DB as the first parameter. In fact, as the documentation clearly states, the first parameter should be a no-arg function returning a connection.
I'm sorry for the erroneous report, and I'm closing this issue.
