### ISSUE TITLE
Open flags

### ISSUE THREAD

**Issue by rongcuid** [JuliaDatabases/SQLite.jl#314]
Please allow open flags to be specified for `SQLite.DB()`. I do not necessarily want to create a new file if path does not exist.

**Comment by metab0t** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/5944 has been merged.

Now you can use [URI file name](https://www.sqlite.org/uri.html) to open SQLite database and specify the mode.

```julia
julia> db = SQLite.DB("file:test.db?mode=ro")
ERROR: SQLiteException("unable to open database file")

julia> db = SQLite.DB("file:test.db?mode=rwc")
SQLite.DB("file:test.db?mode=rwc")
```

**Comment by alhirzel** [comment]
Related - https://stackoverflow.com/questions/64411855/how-to-open-an-sqlite-database-readonly-in-julia
