### ISSUE TITLE
UDFs don't work on ARM

### ISSUE THREAD

**Issue by aplavin** [JuliaDatabases/SQLite.jl#335]
On ARM processors, like Apple Silicon, registering an UDF throws with `cfunction: closures are not supported on this platform`:
```julia
julia> using SQLite
julia> db = SQLite.DB(":memory:")
julia> SQLite.register(db, exp, name="myfunc")
ERROR: cfunction: closures are not supported on this platform
```

This errors both before and after https://github.com/JuliaDatabases/SQLite.jl/pull/333. As I understand, the issue is not in anonymous functions, but in closing over `func` here https://github.com/JuliaDatabases/SQLite.jl/blob/dce0b6c176ab867cc91abc617666f6da3f695a5f/src/UDF.jl#L215-L218

Do not know how to fix this exactly, but should be possible – given discussion at https://github.com/JuliaLang/julia/issues/27174 and in linked issues.

**Comment by metab0t** [comment]
@aplavin Does https://github.com/JuliaDatabases/SQLite.jl/pull/336 solve your problem?

**Comment by metab0t** [comment]
@quinnj Can we release a new version to include recent fixes?
